version: 2

project_name: container-selector

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

brews:
  - name: container-selector
    repository:
      owner: IgorSakharov
      name: homebrew-tap
    homepage: "https://github.com/IgorSakharov/container-selector"
    description: "Interactive Docker container selector and command executor"
    license: "MIT"
    install: |
      bin.install "container-selector"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
